# Generated by Django 5.0.4 on 2024-06-20 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('fetched', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.contest')),
            ],
            options={
                'unique_together': {('handle', 'contest')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('problem_index', models.CharField(max_length=1)),
                ('problem_name', models.CharField(max_length=200)),
                ('programming_language', models.CharField(max_length=50)),
                ('code', models.TextField(blank=True, null=True)),
                ('fetched', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.user')),
            ],
        ),
    ]
