# Generated by Django 5.0.4 on 2024-06-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
